config/routes.rb
Gdrivestrg::Engine.routes.draw do
  resources :params

end

app/models/gdrivestrg/folder.rb
module Gdrivestrg
  class Folder < ActiveRecord::Base
    attr_accessible :folder_name, :remote_id, :user_id

    belongs_to :user, :class_name => Gdrivestrg.user_class
  end
end

app/models/gdrivestrg/param.rb
module Gdrivestrg
  class Param < ActiveRecord::Base
    attr_accessible :expires_in, :issued_at, :refresh_token

    belongs_to :user, :class_name => Gdrivestrg.user_class
  end
end

app/models/gdrivestrg/permission_id.rb
module Gdrivestrg
  class PermissionId < ActiveRecord::Base
    attr_accessible :permission_id, :remoteobject_id, :user_id

    belongs_to :remoteobject
    belongs_to :user, :class_name => Cloudstrg.user_class
  end
end

app/controllers/gdrivestrg/application_controller.rb
module Gdrivestrg
  class ApplicationController < ActionController::Base
  end
end

app/controllers/gdrivestrg/omniauth_callbacks_controller.rb
require 'cloudstrg/cloudstrg'

class Gdrivestrg::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = Kernel.const_get(Gdrivestrg.user_class).find_for_google_oauth2(request.env["omniauth.auth"], current_user)

    if @user.persisted?
    
      _params = {:user => @user, 
             :plugin_id => Cloudstrg::Cloudstrgplugin.find_by_plugin_name("gdrive"), 
             :redirect => "#{request.protocol}#{request.host_with_port}/users/auth/google_oauth2/callback", 
             :refresh_token => request.env["omniauth.auth"].credentials["refresh_token"], 
             :access_token => request.env["omniauth.auth"].credentials["token"], 
             :expires_in => request.env["omniauth.auth"].credentials["expires_at"], 
             :session => session}
      
      driver = CloudStrg.new_driver _params
      _session, url = driver.config _params
      session.merge!(_session)
      
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/gdrivestrg/params_controller.rb
require_dependency "gdrivestrg/application_controller"

module Gdrivestrg
  class ParamsController < ApplicationController
    # GET /params
    # GET /params.json
    def index
      @params = Param.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @params }
      end
    end
  
    # GET /params/1
    # GET /params/1.json
    def show
      @param = Param.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @param }
      end
    end
  
    # GET /params/new
    # GET /params/new.json
    def new
      @param = Param.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @param }
      end
    end
  
    # GET /params/1/edit
    def edit
      @param = Param.find(params[:id])
    end
  
    # POST /params
    # POST /params.json
    def create
      @param = Param.new(params[:param])
  
      respond_to do |format|
        if @param.save
          format.html { redirect_to @param, notice: 'Param was successfully created.' }
          format.json { render json: @param, status: :created, location: @param }
        else
          format.html { render action: "new" }
          format.json { render json: @param.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /params/1
    # PUT /params/1.json
    def update
      @param = Param.find(params[:id])
  
      respond_to do |format|
        if @param.update_attributes(params[:param])
          format.html { redirect_to @param, notice: 'Param was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @param.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /params/1
    # DELETE /params/1.json
    def destroy
      @param = Param.find(params[:id])
      @param.destroy
  
      respond_to do |format|
        format.html { redirect_to params_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/gdrivestrg/application_helper.rb
module Gdrivestrg
  module ApplicationHelper
  end
end

app/helpers/gdrivestrg/params_helper.rb
module Gdrivestrg
  module ParamsHelper
  end
end

app/views/gdrivestrg/_login.html.erb
<%- if devise_mapping.omniauthable? %>
	  <a href='#' onclick="js:google_login('<%= omniauth_authorize_path(resource_name, :google_oauth2) %>', '<%= "#{request.protocol}#{Kernel.const_get(Gdrivestrg.app_name)::Application.config.app_host_and_port}" %>', '<%= "#{request.protocol}#{Kernel.const_get(Gdrivestrg.app_name)::Application.config.app_host_and_port}" %>');" id="btn-sign_in">
		<center><div class="btn btn-info" >
		  <p><%= "Sign in with " %></p>
		  <%= image_tag("gdrivestrg/google.png") %>
		</div></center>
          </a>
<% end -%>

app/views/gdrivestrg/params/_form.html.erb
<%= form_for(@param) do |f| %>
  <% if @param.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@param.errors.count, "error") %> prohibited this param from being saved:</h2>

      <ul>
      <% @param.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :refresh_token %><br />
    <%= f.text_field :refresh_token %>
  </div>
  <div class="field">
    <%= f.label :expires_in %><br />
    <%= f.number_field :expires_in %>
  </div>
  <div class="field">
    <%= f.label :issued_at %><br />
    <%= f.date_select :issued_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gdrivestrg/params/edit.html.erb
<h1>Editing param</h1>

<%= render 'form' %>

<%= link_to 'Show', @param %> |
<%= link_to 'Back', params_path %>

app/views/gdrivestrg/params/index.html.erb
<h1>Listing params</h1>

<table>
  <tr>
    <th>Refresh token</th>
    <th>Expires in</th>
    <th>Issued at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @params.each do |param| %>
  <tr>
    <td><%= param.refresh_token %></td>
    <td><%= param.expires_in %></td>
    <td><%= param.issued_at %></td>
    <td><%= link_to 'Show', param %></td>
    <td><%= link_to 'Edit', edit_param_path(param) %></td>
    <td><%= link_to 'Destroy', param, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Param', new_param_path %>

app/views/gdrivestrg/params/new.html.erb
<h1>New param</h1>

<%= render 'form' %>

<%= link_to 'Back', params_path %>

app/views/gdrivestrg/params/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Refresh token:</b>
  <%= @param.refresh_token %>
</p>

<p>
  <b>Expires in:</b>
  <%= @param.expires_in %>
</p>

<p>
  <b>Issued at:</b>
  <%= @param.issued_at %>
</p>


<%= link_to 'Edit', edit_param_path(@param) %> |
<%= link_to 'Back', params_path %>

app/views/layouts/gdrivestrg/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gdrivestrg</title>
  <%= stylesheet_link_tag    "gdrivestrg/application", :media => "all" %>
  <%= javascript_include_tag "gdrivestrg/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>